## EKS Specific dependency Configuration

command:
  image:
    repository: ''
    tag: ''
    pullPolicy: IfNotPresent

query:
  image:
    repository: ''
    tag: ''
    pullPolicy: IfNotPresent

worker:
  image:
    repository: ''
    tag: ''
    pullPolicy: IfNotPresent

k8s-ingress:
  ingress:
    enabled: true
    className: 'alb'
    annotations:
      # ALB Specific Annotations
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      # URL Rewrite Action for Command Service
      # This takes /command/api/test and forwards it as /api/test
      alb.ingress.kubernetes.io/actions.command-api: >
        {
          "Type": "forward",
          "ForwardConfig": {
            "TargetGroups": [
              {
                "ServiceName": "{{ .Release.Name }}-command",
                "ServicePort": 3001
              }
            ]
          }
        }

      # URL Rewrite Action for Query Service
      alb.ingress.kubernetes.io/actions.query-api: >
        {
          "Type": "forward",
          "ForwardConfig": {
            "TargetGroups": [
              {
                "ServiceName": "{{ .Release.Name }}-query",
                "ServicePort": 3002
              }
            ]
          }
        }

      # URL Rewrite Action for Worker Service
      alb.ingress.kubernetes.io/actions.worker-api: >
        {
          "Type": "forward",
          "ForwardConfig": {
            "TargetGroups": [
              {
                "ServiceName": "{{ .Release.Name }}-worker",
                "ServicePort": 3003
              }
            ]
          }
        }

      # Default 404 Action
      alb.ingress.kubernetes.io/actions.default-404: >
        {
          "Type": "fixed-response",
          "FixedResponseConfig": {
            "ContentType": "application/json",
            "MessageBody": "{\"error\": \"Resource not found\", \"service\": \"gateway\"}",
            "StatusCode": "404"
          }
        }

    defaultBackend:
      serviceName: default-404
      servicePort: 'use-annotation'

    hosts:
      - paths:
          - path: /command
            pathType: Prefix
            serviceName: command-api
            servicePort: 'use-annotation'

          - path: /query
            pathType: Prefix
            serviceName: query-api
            servicePort: 'use-annotation'

          - path: /worker
            pathType: Prefix
            serviceName: worker-api
            servicePort: 'use-annotation'
