name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - demo
          - prod

jobs:
  destroy_infrastructure:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ca-central-1
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.1
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci

      - name: Destroy Infrastructure
        run: npx nx aws:destroy --configuration=${{ inputs.environment }}
